# Generated by Django 5.0 on 2024-01-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
