# Generated by Django 5.0 on 2024-01-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_coupon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='image',
            new_name='code_image',
        ),
        migrations.AddField(
            model_name='coupon',
            name='product_image',
            field=models.ImageField(default='', upload_to='bought_products/'),
        ),
    ]
