# Generated by Django 5.0 on 2024-01-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_coupon_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='combustion_amount',
        ),
    ]
