# Generated by Django 5.0 on 2024-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_bestseller_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='optional_title',
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Station', max_length=100),
        ),
    ]
