# Generated by Django 4.1.5 on 2023-11-21 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_station_name', models.CharField(max_length=100)),
                ('location_url', models.URLField(max_length=255, validators=[django.core.validators.URLValidator()])),
                ('opening_time', models.TimeField(blank=True)),
                ('closing_time', models.TimeField(blank=True)),
                ('is_open_24_hours', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('gas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pumps', to='gas_station.gasstation')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=50)),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=100)),
                ('fuel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_set', to=settings.AUTH_USER_MODEL)),
                ('gas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_set', to='gas_station.pump')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='gas_station.gasstation')),
            ],
        ),
        migrations.CreateModel(
            name='SystemController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_prices', models.JSONField()),
                ('gas_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_controller', to='gas_station.gasstation')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('owner_from', models.DateTimeField(auto_now_add=True)),
                ('other_information', models.TextField(blank=True)),
                ('billing_address', models.CharField(max_length=100)),
                ('gas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='gas_station.gasstation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('gas_station', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='gas_station.gasstation')),
            ],
        ),
    ]
