# Generated by Django 4.2.7 on 2023-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontroller',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
