# Generated by Django 5.0 on 2024-01-22 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0004_pump_pump_number_tank_tank_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=100)),
                ('fuel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_transaction_set', to=settings.AUTH_USER_MODEL)),
                ('gas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_transaction_set', to='gas_station.pump')),
            ],
        ),
    ]
