# Generated by Django 5.0 on 2024-01-22 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0005_createdtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatedTransaction',
            new_name='TransactionInProccess',
        ),
    ]
