# Generated by Django 5.0 on 2024-01-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0007_rename_gas_station_transaction_pump_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gas_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_set', to='gas_station.gasstation'),
        ),
        migrations.AddField(
            model_name='transactioninproccess',
            name='gas_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_in_proccess', to='gas_station.gasstation'),
        ),
    ]
