# Generated by Django 5.0 on 2024-01-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0008_transaction_gas_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gas_station',
        ),
        migrations.RemoveField(
            model_name='transactioninproccess',
            name='gas_station',
        ),
    ]
