# Generated by Django 5.0 on 2024-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0009_remove_transaction_gas_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcontroller',
            name='fuel_prices',
        ),
        migrations.AddField(
            model_name='systemcontroller',
            name='diesel_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='systemcontroller',
            name='electric_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='systemcontroller',
            name='petrol_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
