# Generated by Django 5.0 on 2024-03-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0010_remove_systemcontroller_fuel_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='is_ready_to_pay',
            field=models.BooleanField(default=False),
        ),
    ]
