# Generated by Django 5.0 on 2024-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_station', '0011_pump_is_ready_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='is_payment_in_process',
            field=models.BooleanField(default=False),
        ),
    ]
